version: "2.1"
volumes:
    postgres:

services:
    postgres:
        build:
            context: postgresql
            args:
                POSTGRES_RELEASE: ${POSTGRES_RELEASE}
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - postgres:/var/lib/postgresql/data
        restart: unless-stopped

    api:
        build:
            context: api
            args:
                SRC_DIR: ${API_DIR}
        environment:
            PGHOST: postgres
            PGUSER: ${POSTGRES_USER}
            PGPASSWORD: ${POSTGRES_PASSWORD}
            PGOPTIONS: "-c myproject.encrypt_key=${PG_ENCRYPTION_KEY}"
        ports:
            - 8000:8000
        volumes:
            - ${API_DIR}:/code
        depends_on:
            - postgres
